### PR TITLE
Webserver moved to separate directory to avoid conflicts with original TON sources

### PR DESCRIPTION
**Pull request by adastreamer**

### CODE REVIEW

**Comment by skywinder** [comment]
Awesome, @adastreamer 
 would you mind adding a tine description & howto to README.md?

**Review by skywinder — APPROVED** [review]
In addition: A small update of readme with link to documentation would be great!

**Comment by skywinder** [comment]
description added by @IrKor in #23
Thank you, buildlers!

**Comment by IrKor** [comment]
> In addition: A small update of readme with link to documentation would be great!

I added a link to the doc here https://github.com/adastreamer/TON/pull/5 ;)

**Pull request merged**
